version: '3'
services:
  drupal:
    image: drupal:10-apache
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.boilerplate-drupal.localhost'
    expose:
      - 80
    volumes:
      - ./:/opt/drupal
    restart: always

  solr1:
    image: solr:8
    container_name: boilerplate-drupal-solr1
    restart: always
    expose:
      - 8983
    environment:
      SOLR_OPTS: -Djute.maxbuffer=50000000
      ZK_HOST: boilerplate-drupal-zoo1:2181
      SOLR_HEAP: 1g
    labels:
      - 'traefik.backend=solr'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:solr.boilerplate-drupal.localhost'
    depends_on:
      - zoo1
    volumes:
      - ./solr-cloud/security.json:/var/security.json
      - .:/mnt/config
      - solr1:/var/solr
    command: bash -c "docker-entrypoint.sh solr zk cp file:/var/security.json zk:/security.json && exec solr-foreground"

  zoo1:
    image: zookeeper:3.6
    container_name: boilerplate-drupal-zoo1
    hostname: boilerplate-drupal-zoo1
    restart: always
    expose:
      - 2181
      - 7000
    environment:
      # The pre-trained OpenNLP models require a much bigger buffer.
      JVMFLAGS: -Djute.maxbuffer=50000000
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=boilerplate-drupal-zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    volumes:
      - .:/mnt/config
volumes:
  solr1:
